### ISSUE TITLE
After plugin connects to AC Unit, temperature is displayed in Celsius, even if set to Fahrenheit 

### ISSUE THREAD

**Issue by PMacDiggity** [hillaliy/homebridge-midea-air#10]
It seems the plugin pushes a Celsius config to the Midea API, and thereby to the AC unit

- If I use the Midea app to configure the AC unit to display in Fahrenheit, and then launch Homebridge to connect to it, it reverts to displaying in Celsius.
- Launching the Midea app to reconfigure the unit to Fahrenheit breaks the Homebridge plugin connection, and the unit returns to Celsius when reconnected to Homebridge plugin.
- If I change the display to Fahrenheit on the unit using the physical buttons, it reverts back to Celsius any time an update from Homebridge is sent (such as changing the temperature)

**Comment by hillaliy** [comment]
Hi this is No an issue.
This Plugin only support Celsius for now.
