### ISSUE TITLE
Multiple devices

### ISSUE THREAD

**Issue by Draexl** [hillaliy/homebridge-midea-air#101]
Hi,
What should the code look like if I have multiple devices?

    {
      "registeredApp": "NetHomePlus",
      "user": "username",
      "password": "password",
      "interval": 5,
      "devices": [
        {
                "deviceId": "firstDeviceID",
                "supportedSwingMode": "Both",
                "temperatureSteps": 1,
                "minTemp": 17,
                "maxTemp": 30,
                "fanOnlyMode": false,
                "OutdoorTemperature": false,
                "useFahrenheit": false,
                "audibleFeedback": false
        }
        {
                "deviceId": "secondDeviceID",
                "supportedSwingMode": "Both",
                "temperatureSteps": 1,
                "minTemp": 17,
                "maxTemp": 30,
                "fanOnlyMode": false,
                "OutdoorTemperature": false,
                "useFahrenheit": false,
                "audibleFeedback": false
        }
      ],
      "platform": "midea-air"
    },

Is that correct?

**Comment by hillaliy** [comment]
Yes, but don't use the interval so low. I recommended to change it to 30
