### ISSUE TITLE
Nothing happens under hoobs 4.2.8

### ISSUE THREAD

**Issue by The-Paw** [hillaliy/homebridge-midea-air#104]
`{
    "platform": "midea-air",
    "interval": 30,
    "user": "***",
    "password": "***",
    "devices": [
        {
            "deviceId": "340E7395603211502J0002",
            "supportedSwingMode": "Vertical",
            "fanOnlyMode": true
        },
        {
            "deviceId": "34079477002950402M1066",
            "supportedSwingMode": "None",
            "fanOnlyMode": true
        }
    ]
}`

What is the DeviceID ??   "deviceId": "340E7395603211502J0002" was the S/N from the device ..

Hoobs Log
`25.11.2022, 19:38:37HOOBSLoaded plugin 'homebridge-broadlink-rm-pro'
25.11.2022, 19:38:38HOOBSLoaded plugin 'homebridge-eveatmo'
25.11.2022, 19:38:39HOOBSLoaded plugin 'homebridge-midea-air'
25.11.2022, 19:38:40HOOBSLoaded plugin 'homebridge-xiaomi-fan'
25.11.2022, 19:38:40HOOBSLoading 5 platforms...`

Nothing happens after this from the midea-air plugin !!

**Comment by hillaliy** [comment]
I didn't test this plugin on hoobs.
send debug log from hoobs.

**Comment by The-Paw** [comment]
[log.txt](https://github.com/hillaliy/homebridge-midea-air/files/10094984/log.txt)

**Comment by hillaliy** [comment]
There is nothing on the log that I can use.
Sorry, I recommended to use Homebridge image instead Hoobs

**Comment by The-Paw** [comment]
> There is nothing on the log that I can use.
> Sorry, I recommended to use Homebridge image instead Hoobs

Soo .. why is the PlugIn listed here: https://plugins.hoobs.org/plugin/homebridge-midea-air

How can I find the Device ID ??

**Comment by The-Paw** [comment]
> There is nothing on the log that I can use.
> Sorry, I recommended to use Homebridge image instead Hoobs

And I´ve a hoobs box .. so, no other image.

**Comment by hillaliy** [comment]
I didn't add the plugin to hoobs. They maybe add it.

**Comment by The-Paw** [comment]
Before reseting my hoobs, the plugin works great .. so I search myself for the problem :-((

**Comment by hillaliy** [comment]
good luck!

**Comment by The-Paw** [comment]
> good luck!

Again the question .. where can I find the Device ID?

**Comment by hillaliy** [comment]
https://github.com/hillaliy/homebridge-midea-air#%EF%B8%8F-optional-per-device-configuration-values

**Comment by The-Paw** [comment]
Update to 1.7.3 and it is working without any changes by myself ..

**Comment by hillaliy** [comment]
Good to hear.
