### ISSUE TITLE
Better mapping of the relative humidity

### ISSUE THREAD

**Issue by Dakyne** [hillaliy/homebridge-midea-air#107]
Hi! First of all thanks for your plugin, it works great.

I'd have a request, would it be possible to choose to map relative humidity an other way ? Something like this so for example 65% on HomeKit is 65% on midea:

| Midea | Homekit |
| ----- | ------- |
| 35% | 0% |
| 35% | 5% |
| 35% | 10% |
| 35% | 15% |
| 35% | 20% |
| 35% | 25% |
| 35% | 30% |
| 35% | 35% |
| 40% | 40% |
| 45% | 45% |
| 50% | 50% |
| 55% | 55% |
| 60% | 60% |
| 65% | 65% |
| 70% | 70% |
| 75% | 75% |
| 80% | 80% |
| 85% | 85% |
| 85% | 90% |
| 85% | 95% |
| 85% | 100%|

I think HomeKit can only do 10% steps, but you got the idea.

You could set an offset_humidity:true option to enable or disable.

Anyway, thanks for reading, if you don't care about it please close it, I'll be able to live without it!

**Comment by hillaliy** [comment]
After a lot of testing believe me it's the best
