### ISSUE TITLE
Was working. Maybe this will help.

### ISSUE THREAD

**Issue by Sledneck54** [hillaliy/homebridge-midea-air#109]
I have 6 Midea wall cassettes. I purchased 1 US-SK105 dongle. 
It worked with Homebridge installed on my Mac. 
I purchased 5 more. At the same time I moved Homebridge to my Synology NAS. Started fresh. Bridged to HomeKit. This configuration won't control any of my units. They all show up in HomeKit, I can change the temperature and what setting to run but the wall cassette never responds. I guess it times out. 
I've even logged out of the Midea App. I also tried the Net home app. Same thing.
Homebridge is running as a Synology package. 

I'll try running Homebridge again on my Mac and see if the functionality returns.

**Comment by hillaliy** [comment]
Hi, can you send debug logs from your Mac

**Comment by Sledneck54** [comment]
I did ask if dry mode could be enabled previously. All other modes did work when I only had the one cassette linked to my app.  
I wish I could duplicate to help this project. The US-SK105 did work.
I apologize. I wish I understood coding better to help resolve this issue.

**Comment by hillaliy** [comment]
send me in private (Discord) your username and password I'll try to take some logs from your devices.

**Comment by hillaliy** [comment]
No luck for now.
There is an open issue to add support for OSK105.
I'm closing this issue.
