### ISSUE TITLE
Login Error in Homebridge Debug Log

### ISSUE THREAD

**Issue by Seexelas** [hillaliy/homebridge-midea-air#110]
Hi,

My AC was installed and I configured it with MSmart Home APP, everything is ok from this side. 

I installed the plugin in my Homebridge environnement, I did the setup and I'm getting this error : 

[12/16/2022, 2:33:00 PM] [homebridge-midea-air] Login request failed with: TypeError: Cannot read properties of undefined (reading 'loginId')
[12/16/2022, 2:33:00 PM] [homebridge-midea-air] Login failed

Here is my configuration script :

--------------------------------------------------------

       {
            "user": "alexis.conrad@XXXX.com",
            "password": "XXXXXXX",
            "registeredApp": "MSmartHome",
            "interval": 30,
            "devices": [
                {
                    "supportedSwingMode": "Both",
                    "temperatureSteps": 1,
                    "minTemp": 17,
                    "maxTemp": 30,
                    "fanOnlyMode": true,
                    "OutdoorTemperature": true,
                    "useFahrenheit": false,
                    "audibleFeedback": true
                }
            ],
            "_bridge": {
                "username": "0E:E8:D1:A4:96:B9",
                "port": 30402
            },
            "platform": "midea-air"
        }
    ],
    "disabledPlugins": [
        "homebridge-adb"
    ] 

My Homebridge : 

(Running in a VM on Hyper-V)
OS	Ubuntu Focal Fossa (20.04.5 LTS)
Hostname	homebridge-vm
IPv4 (eth0)	192.168.1.248
IPv6 (eth0)	fd3e:f481:ea65:4e3d:215:5dff:fe01:fb03
Node.js Version	v18.12.0
User	root
Storage Path	/var/lib/homebridge
Config Path	/var/lib/homebridge/config.json
OS | Ubuntu Focal Fossa (20.04.5 LTS)
-- | --
homebridge-vm
192.168.1.248
fd3e:f481:ea65:4e3d:215:5dff:fe01:fb03
v18.12.0
root
/var/lib/homebridge
/var/lib/homebridge/config.json
--------------------------------------------------------

Did I miss something ?

Many thanks, take care !

**Comment by hillaliy** [comment]
https://github.com/hillaliy/homebridge-midea-air#%EF%B8%8F-knowing-issues

**Comment by Seexelas** [comment]
Thanks for the answer, so I need to change the application right ?

**Comment by Seexelas** [comment]
I installed Midea Air, it's working ! THanks
