### ISSUE TITLE
Create automation with indoor temperature of the AC

### ISSUE THREAD

**Issue by Seexelas** [hillaliy/homebridge-midea-air#113]
Hi, 

For my setup, my AC indoor temp is shown this way when the AC is off : 

![IMG_0164](https://user-images.githubusercontent.com/64669806/209683487-1f1b610b-5dc3-4703-9f5c-8ec09225344b.PNG)

When it's on : 

![IMG_0163](https://user-images.githubusercontent.com/64669806/209683530-a9d16f68-836f-4d72-acfd-5b2457ba6603.PNG)

Indoor temp is shown in the corner, and the the temp set on the AC is shown in the middle.

For an automation into Home. I can only select the outdoor temp sensor, there is no indoor temp sensor. 

Is this possible to be added or fixed ?

Many thanks,

**Comment by hillaliy** [comment]
Hi this is not a bug.
It's supposed to work like this (HomeKit HeaterCooler).
The outdoor sensor temperature is a separate accessory.

**Comment by Seexelas** [comment]
Thanks for the answer.

So what can I do to trigger an automation with indoor temp ?

**Comment by Seexelas** [comment]
What i meant is to have the possiblity for a separate accessory for the **indoor temperature** because without this, you can not create an automation based on this temperature.

I want to be able that if the indoor temp. goes below 14 degrees C., the AC starts at 17 degrees. 

Do you think something is possible please ?

**Comment by hillaliy** [comment]
Download Eve for HomeKit

https://apps.apple.com/il/app/eve-for-homekit/id917695792?l=iw

And then make a rule
