### ISSUE TITLE
OSK103 Issue - Not sending Commands

### ISSUE THREAD

**Issue by Clayton1212** [hillaliy/homebridge-midea-air#115]
Hi,

thank you very much for all your work on this plugin. I am not a coder by any means so I appreciate this very much
I really hope you can assist me with this problem. I see originally your plugin did not support OSK103, then you changed it to support OSK103. Unfortunately my 2 split aircons using the OSK103 do not work and I can't figure out why. I can only see the status of them in Homebridge, but cannot send commands.

Please please can you help? thank you

**Comment by hillaliy** [comment]
Hi
Check if your device is: Mission II / Blanc
There is an open issue for those models

**Comment by Clayton1212** [comment]
ok thank you will do. How/where do I find out if the device is Mission II / Blanc?

**Comment by Clayton1212** [comment]
sorry for my ignorance. still new at this. If I understand correctly, then no my device is not a Mission II or Blanc. It is a Midea Xtreme. (https://aircon.mideasouthafrica.com/room-range/midwall-split/xtreme/)

The Model number is MSAGB-12HRN1-QC0

I hope this helps

**Comment by hillaliy** [comment]
Your model is Blanc

**Comment by Clayton1212** [comment]
oh wow that's unfortunate. how did you find that? when I purchase new ones in the future I will make sure to check that. For now I will follow your Issue already existing "Add Midea Mission II / Blanc / OSK105 support #3"

thanks for your help

**Comment by hillaliy** [comment]
You welcome

**Comment by Clayton1212** [comment]
how do you find the model on the unit? I would like to check what others are available in my market

**Comment by hillaliy** [comment]
Google Search!
https://www.dealayo.com/midea-1-0-ton-wall-mounted-air-conditioner-msaga-12hrn1.html
BRAND: MIDEA
Model: MSAGB-12HRN1
Type: Wall-mounted air conditioner;
Technology: Constant type of air conditioner;
Long Distance Airflow
Series: Midea Blanc
Energy Class: А+
Cooling SEER: 6.2
Heating SCOP: 5.1
Capacity: 9000 Btu
Flash Cool for providing instant cooling
Low-profile design for matching with decor

**Comment by Clayton1212** [comment]
that's very interesting thank you. When I did a google search that didn't pop up. I think Midea calls the model Xtreme here in Africa but is likely the same thing as Blanc elsewhere
