### ISSUE TITLE
OSK103 support

### ISSUE THREAD

**Issue by jefflewis** [hillaliy/homebridge-midea-air#13]
~Having this change the unit of measurement is less than ideal.~

OSK103 is not well supported. Some functions (like changing temperature units) do not work reliably.

**Comment by jefflewis** [comment]
If I knew all of the key places to add the conversion, I'd update with a PR to add support.

**Comment by nickhudkins** [comment]
Hey @jefflewis this is something I am actually looking into right now. While I can set it over and over (using the remote), it is frustrating that it pretty consistently reverts to ºC.

I'm hoping to have a PR up today

**Comment by jefflewis** [comment]
Lemme know if I can help!

**Comment by hillaliy** [comment]
Hi, On my unit it's work just fine.
I have OSK102 dongle.
Check if your device have OSK103 dongle.
The commands is different on OSK103.

**Comment by jefflewis** [comment]
@hillaliy When you say "work just fine" do you mean that it successfully changes the display of units on the unit to ºC whenever the home bridge plugin launches? Because that is exactly what happens.

This issue was meant to track making this plugin _not_ need to do that.

**Comment by jefflewis** [comment]
I do have the OSK103 dongle. Should the issues description be `ºF Support for OSK103 smart kit module`?

**Comment by hillaliy** [comment]
If you restart Homebridge the plugin returns to default and the default is Celsius.
And ass I wrote this plugin don't support OSK103 dongle.
The plugin will connect to Midea cloud and create your devices but not control properly. Midea change the commands protocol.

**Comment by jefflewis** [comment]
What is necessary to get the new module working? I can help add support if needed.

**Comment by hillaliy** [comment]
Try to find the New Midea API

**Comment by jefflewis** [comment]
By "find the new Midea API", do you mean some new API response handler to handle the current remote API (https://mapp.appsmb.com/v1), a local network API server run by the OSK103 module, or a new remote API that is separate from the currently supported one? (https://mapp.appsmb.com/v1)

**Comment by hillaliy** [comment]
I mean the new command protocol

**Comment by jefflewis** [comment]
Awesome. I'm guessing that means add a new OSK103 device type to this switch the a new data array?

src/BaseCommand.ts

Where did you get the original ask docs for the current data arrays? That might be helpful in finding the new values.

Thanks!

**Comment by hillaliy** [comment]
Midea iobroker

**Comment by hillaliy** [comment]
I use this also
[Midea T0xAC.zip](https://github.com/hillaliy/homebridge-midea-air/files/6606124/Midea.T0xAC.zip)
[Midea T0xE3.zip](https://github.com/hillaliy/homebridge-midea-air/files/6606126/Midea.T0xE3.zip)

**Comment by hillaliy** [comment]
Try Version 1.2.8

**Comment by qweluke** [comment]
@jefflewis @hillaliy hi guys, how it's going with 103 dongle?
I wonder If I can help you somehow...

**Comment by hillaliy** [comment]
It will be helpful If i have a 103 dongle to test

**Comment by hillaliy** [comment]
If you can give me access to your AC

**Comment by qweluke** [comment]
@hillaliy I can share with you midea login credentials. Would it be helpfull to you?

**Comment by hillaliy** [comment]
I'll appreciate if you send me in private your account.
I'll try to get feedback from one of your AC. About dry i didn't add support, if it needed i can add.

**Comment by hillaliy** [comment]
Auto mode should show range. The air conditioner maintains a set temperature. If the temperature is below the set it will heat up otherwise it will cool down.
Besides, everything seems fine.
As for drying mode, I can add support I need some time and motivation.
