### ISSUE TITLE
Invalid session error

### ISSUE THREAD

**Issue by adamsimon** [hillaliy/homebridge-midea-air#15]
I'm getting the following error when Homebridge is attempting to refresh the device status, or control the device.

[MideaPlatform.ts] sendCommand (Intent: [updateValues] (fetch params?) attempt 1/2) returned error invalidSession, 3106

I have double checked the login information and device IDs, which are correct, and on initial startup of Homebridge, it pulls the correct temperature information from the device, it is just unable to update or control the device after initial startup. I have two Midea U Inverter Window Air Conditioners, model MAW08V1QWT. Also, the error always says "attempt 1/2", there is never an "attempt 2/2".

**Comment by hillaliy** [comment]
Please check your dongle version

**Comment by adamsimon** [comment]
There is no dongle, the unit natively supports wifi. It had worked correctly in a previous version of the plugin.

**Comment by cojoj** [comment]
Hey! Same here for me as well. However, I'm using Rotenso AC units. Strangely, up until yesterday, everything worked perfectly fine. Today it stopped working, and after updating the plugin to `1.2.4` still giving me an error.

**Comment by hillaliy** [comment]
Good to hear

**Comment by adamsimon** [comment]
Oh I definitely tried restarting, and I just tried it again. No luck, still receiving an invalid session error, and the devices do not respond to commands. It's still able to read the temperature from the devices, but it may not be updating, just reading that on Homebridge restart.

**Comment by PMacDiggity** [comment]
I am also having this issue. Restarting seems to fix it temporarily, but the issue reoccurs after less that 24hrs.

**Comment by cojoj** [comment]
@adamsimon, @PMacDiggity have you maybe modified the `interval` property? When I used a different plugin back in the days, the problem was that it was hitting their API too often, and my account was always in this unresponsive state.

**Comment by hillaliy** [comment]
I also saw it. I'm tasting it since tomorrow. until now everything OK at my HVAC.
I recommend that the interval be no less than 30 seconds.

**Comment by hillaliy** [comment]
Try version 1.2.5
