### ISSUE TITLE
Issues with controlling Midea U Window Units

### ISSUE THREAD

**Issue by robertirish** [hillaliy/homebridge-midea-air#16]
Basic functionality is working correctly—Siri is able to turn the units on and off, and can set the temperature of the units.

The following functions aren’t accessible by Siri / through the HomeKit app:

- change fan speed (reverts immediately to max/auto)
- change mode between cool/heat/auto
- change temperature unit

Is this the same issue as the OSK103 problems?

**Comment by hillaliy** [comment]
Yes. It's look like there are the same new protocol

**Comment by robertirish** [comment]
I thought so. Any idea on if this will be able to be fixed in the
near future?

Thanks for your amazing work on this.

**Comment by hillaliy** [comment]
I'm trying to find the new protocols

**Comment by jakemauer** [comment]
I have one of these units, let me know if I can be helpful by providing wireshark logs etc.

**Comment by vdotn** [comment]
+1 for requesting window unit support for the Midea U. I'm open to helping as well!

**Comment by hillaliy** [comment]
Hi try to install Home-Assistant and then this plugin:
https://pypi.org/project/midea-andersonshatch/
let me know if it's work with your AC.

**Comment by hillaliy** [comment]
Try Version 1.2.8

**Comment by brycerudyk** [comment]
1.2.8 doesn't work with the U units. It constantly resets the temperature to the minimum, puts it in auto mode instead of cooling, forces you to re-login to the Midea app and has characteristic warnings in the Homebridge log every 5 seconds:

This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 17. See https://git.io/JtMGR for more info.
[7/19/2021, 10:45:10 AM] [homebridge-midea-air] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 17. See https://git.io/JtMGR for more info.

1.2.7 didn't have much functionality, but it generally worked for the U units. Is there anything that I can do to help?

**Comment by hillaliy** [comment]
send homebridge log

**Comment by Tesla-P100FX** [comment]
i am having the same issue

**Comment by Tesla-P100FX** [comment]
7/21/2021, 3:48:49 PMMidea Air Bridge starting
7/21/2021, 3:48:53 PMMidea Air BridgeLoaded plugin 'homebridge-midea-air'
7/21/2021, 3:48:53 PMMidea Air BridgeLoading 1 platforms...
7/21/2021, 3:48:53 PMMidea Air Bridgemidea-airLoading accessory from cache: Master bed Air
7/21/2021, 3:48:53 PMMidea Air BridgeBridge is running on port 55826.
7/21/2021, 3:48:54 PMMidea Air Bridgemidea-airCreated device: Master bed Air, with ID: 34084860486000, and type: 172
Midea Air Bridgemidea-air[MideaPlatform.ts] sendCommand (Intent: [updateValues] (fetch params?) attempt 1/2) returned error invalidSession, 3106
7/21/2021, 3:53:09 PMOmnilink Platform BridgeOmniAuxiliarySensor 16 [Thermostats]: 4C
7/21/2021, 3:53:24 PMMidea Air Bridgemidea-air[MideaPlatform.ts] sendCommand (Intent: [updateValues] (fetch params?) attempt 1/2) returned error invalidSession, 3106
7/21/2021, 3:53:39 PMOmnilink Platform BridgeOmniAuxiliarySensor 16 [Thermostats]: 8.5C
7/21/2021, 3:53:54 PMMidea Air Bridgemidea-air[MideaPlatform.ts] sendCommand (Intent: [updateValues] (fetch params?) attempt 1/2) returned error invalidSession, 3106
7/21/2021, 3:54:09 PMOmnilink Platform BridgeOmniAuxiliarySensor 16 [Thermostats]: 4C
7/21/2021, 3:54:24 PMMidea Air Bridgemidea-air[MideaPlatform.ts] sendCommand (Intent: [updateValues] (fetch params?) attempt 1/2) returned error invalidSession, 3106
7/21/2021, 3:54:39 PMOmnilink Platform BridgeOmniAuxiliarySensor 16 [Thermostats]: 8C
7/21/2021, 3:54:54 PMMidea Air Bridgemidea-air[MideaPlatform.ts] sendCommand (Intent: [updateValues] (fetch params?) attempt 1/2) returned error invalidSession, 3106
7/21/2021, 3:55:09 PMOmnilink Platform BridgeOmniAuxiliarySensor 16 [Thermostats]: 4C
7/21/2021, 3:55:24 PMMidea Air Bridgemidea-air[MideaPlatform.ts] sendCommand (Intent: [updateValues] (fetch params?) attempt 1/2) returned error invalidSession, 3106
7/21/2021, 3:55:39 PMOmnilink Platform BridgeOmniAuxiliarySensor 16 [Thermostats]: 4.5C
7/21/2021, 3:55:55 PMMidea Air Bridgemidea-air[MideaPlatform.ts] sendCommand (Intent: [updateValues] (fetch params?) attempt 1/2) returned error invalidSession, 3106
7/21/2021, 3:56:09 PMOmnilink Platform BridgeOmniAuxiliarySensor 16 [Thermostats]: 4C
7/21/2021, 3:56:24 PMMidea Air Bridgemidea-air[MideaPlatform.ts] sendCommand (Intent: [updateValues] (fetch params?) attempt 1/2) returned error invalidSession, 3106
7/21/2021, 3:56:39 PMOmnilink Platform BridgeOmniAuxiliarySensor 16 [Thermostats]: 8.5C
7/21/2021, 3:56:54 PMMidea Air Bridgemidea-air[MideaPlatform.ts] sendCommand (Intent: [updateValues] (fetch params?) attempt 1/2) returned error invalidSession, 3106

**Comment by larryang** [comment]
I also ave a Midea U, and am also getting similar errors to 'Heating Threshold Temperature'. I downgraded from  1.2.9 to 1.2.7  to get some functionality.

Attached is the /var/lib/homebridge/homebridge.log  from  running  v1.2.9 - I scrubbed the IDs with XXXs.
[midea_u.txt](https://github.com/hillaliy/homebridge-midea-air/files/6871818/midea_u.txt)

**Comment by hillaliy** [comment]
the packages on 1.2.7 & 1.2.9 is the same.
send me log from 1.2.7

**Comment by larryang** [comment]
> the packages on 1.2.7 & 1.2.9 is the same.
> send me log from 1.2.7

[midea_u_1_2_7_log.txt](https://github.com/hillaliy/homebridge-midea-air/files/6872395/midea_u_1_2_7_log.txt)

**Comment by hillaliy** [comment]
i'm testing a U Unit that work with 1.2.9

**Comment by NOTaMango** [comment]
Hey I'm on 1.3.5, on a U window unit. I've noticed this since I started using this plugin. If I set the temperate units to Fahrenheit in homekit, it reverts to Celsius when I initiate any other commands. Not a biggy, and possible it's a homekit bug, but thought I'd mention it.

Thanks!

**Comment by hillaliy** [comment]
I'm using Midea AC with OSK102. it's work just fine. The command on Midea U and all OSK103 family is a little bit different.
Dose your AC response to other commands?

**Comment by hillaliy** [comment]
Go to - Add Midea Mission II / U support
