### ISSUE TITLE
Plugin switches temp units to C 

### ISSUE THREAD

**Issue by bpengu1n** [hillaliy/homebridge-midea-air#2]
Seems when sending a temp change to the AC (when units are set to F, of course), it automatically switches the AC's units to C. Recommend a config setting to ID desired units for those of us still stuck in the past ;)

**Comment by hillaliy** [comment]
knowing problem. Hope to fix it in the next Update.

**Comment by hillaliy** [comment]
The plugin won't support Fahrenheit for now.
