### ISSUE TITLE
Plugin seems to not re-authenticate

### ISSUE THREAD

**Issue by huanga** [hillaliy/homebridge-midea-air#20]
Hey there;

I'm seeing a lot of this in my logs (entry at every configured update interval):

``` 
[midea-air] [MideaPlatform.ts] sendCommand (Intent: [updateValues] (fetch params?) attempt 1/2) returned error invalidSession, 3106
```

I'm not a JS/TypeScript dev, so I don't think I can submit a PR, but I think MideaPlatform.js calls sendCommand when trying to update the devices' statuses [here](https://github.com/hillaliy/homebridge-midea-air/blob/main/lib/MideaPlatform.js#L365) in a try catch, which should handle the re-authentication process, but the error doesn't seem to be bubbling up?  In other languages I'm familiar with, when an error is caught (in this case, within [sendCommand](https://github.com/hillaliy/homebridge-midea-air/blob/0180005d9ac231e078bb13317f3e8ee8b1376e0f/src/MideaPlatform.ts#L303)) it doesn't get bubbled up to the calling function. Does `reject()` in JS/TypeScript enable for this, or does it still need to be thrown?

Initially, I thought if I launch the app on my phone, it would invalidate my session. But even after being very careful not launching the app, it seems to pop up, and I'm not sure how to mitigate it. Would be great if we can get to the bottom of this and have the plugin re-authenticate automatically so I don't need to restart my HomeBridge every so often to keep this in sync.

Thanks!

**Comment by huanga** [comment]
Sorry, forgot to mention, I'm on 1.3.4: 

```
    "homebridge-midea-air": "^1.3.4",
```

**Comment by hillaliy** [comment]
What is your AC model?

**Comment by huanga** [comment]
The device is Danby DAP120B9IBDB-6, which is a rebrand of Midea MP12SVWBA3RCM. The plugin identifies it as:

```
[midea-air] Created device: Office, with ID: 30786325787715, and type: 172
```

I have the app installed, but once I have Homebridge activated, I force quit the app and make sure it is not running. The plugin checks and works for a few hours, and then throws that message. It also seems to throw intermittent error as:

```
Command was not accepted by device: Office (30786325787715)
```

However, the command message does not seem to be directly related to this authentication error as it continues to work fine for several more hours until it fails again.

**Comment by hillaliy** [comment]
According to Midea this model has US-OSK103 Wifi module. My plugin don't support yet this module. It will create accessory but won't function properly.

**Comment by huanga** [comment]
Sorry, work ramped up and I missed the reply.

Aside from what I've already shared, there's nothing else related to this plugin, which is why I am thinking it has to do with the try/catch handling. I guess it is better to know that this is result of unsupported module, and will hopefully eventually be supported.

Thanks!
