### ISSUE TITLE
Command was not accepted by device: Master bedroom (16492674477782)

### ISSUE THREAD

**Issue by darthwiniar** [hillaliy/homebridge-midea-air#21]
Hi. Devices(Midea wall AC) not responding in homebridge. Console:Command was not accepted by device: Master bedroom (16492674477782). How to fix it?

**Comment by hillaliy** [comment]
Send me your AC model

**Comment by darthwiniar** [comment]
Midea Blanc 3.5 KW

**Comment by hillaliy** [comment]
your model is Midea Mission II
you can get feedback but not send command
I hope to add more models support to my plugin
