### ISSUE TITLE
Midea account email and supported device

### ISSUE THREAD

**Issue by MrksHfmn** [hillaliy/homebridge-midea-air#23]
Thank you for your effort and this plugin! I have two questions:

1. How can I create the Midea account?
2. I own a Midea Comfee MDDF-16DEN7-WF dehumifier. Is it supported?

Thanks and best regards!

**Comment by hillaliy** [comment]
Hi download Midea app on your iPhone.
Create an account and add Your dehumidifier to the app.
then close the app and enter your user name and password on Homebridge Midea Air plugin.
If thre device have osk102 it will work.
I recommend to try
