### ISSUE TITLE
Did Midea change their API? Nothing works now!

### ISSUE THREAD

**Issue by jackklink** [hillaliy/homebridge-midea-air#25]
It seems that something has gone awry with Midea’s API causing all the plugins for Midea ACs to stop working. This plug-in and another one both use to work, but now neither of them do as of today.

**Comment by hillaliy** [comment]
There was a  problem since yesterday. but now it's work. try restart homebridge

**Comment by jackklink** [comment]
Ok yes while trying to fix the issue I moved my devices to the MSmartLife app so that’s why it stopped working. Moved back to the Midea Air app and all good now. Thanks!

**Comment by jackklink** [comment]
It is no longer working again. Hmm 🤔

**Comment by hillaliy** [comment]
works perfect for me.
don't use midea app and homebridge simultany. you can use NetHome Plus app

**Comment by jackklink** [comment]
I’m not using Midea app and I logged out of it even but nothing is working suddenly via the home app.

**Comment by jackklink** [comment]
Controlling from the home app does nothing, but the logs show no errors. I’ve changed nothing in my config since earlier today when it was working fine. 

Uploading IMG_1146.MP4…

**Comment by jackklink** [comment]
Now I get this error in the Midea air app. I’ve never had so many issues with this until the past few days and I’ve been using hombridge with these ACs for a year now. Any help would be greatly appreciated! 

![ADE8E477-ACFC-4D34-AD72-535E8E056FBF](https://user-images.githubusercontent.com/2200283/134454301-c688e352-7e4e-4c13-80ca-0daef8251b9a.png)

**Comment by hillaliy** [comment]
I think it's something with your account.
