### ISSUE TITLE
[midea-air] Command was not accepted by device

### ISSUE THREAD

**Issue by mpetto** [hillaliy/homebridge-midea-air#26]
Hello,
first of all thank you for this plugin :)

I open a ticket because it is impossible for me to control my A / C Carrier splits with OSK103 dongle .. I have installed the latest version (1.3.9).

For information, the temperatures rise correctly, but impossible to modify any parameter.

The logs indicate :

"**[midea-air] [MideaPlatform.ts] sendCommand (Intent: [updateValues] (fetch params?) attempt 1/2) returned error invalidSession, 3106**"

"**[05/10/2021, 15:41:56] [midea-air] Command was not accepted by device: XXX (31885837434139)**"

Any solution?

Thank you very much for your help and your work :)

**Comment by hillaliy** [comment]
Hi, If your Device is midea U model, it doesn't work correctly with this plugin. you only can get state from the AC.
hope to add support for this model.

**Comment by mpetto** [comment]
Thank you for your response.

I don’t know that my models are U Midea. They are Carrier brand with Carrier Dongle (OSX103 model). They are contrôlable by Carrier and Midea app and account.

I send you my account informations if you want.

Good luck :)

**Comment by hillaliy** [comment]
Send me your AC model

**Comment by mpetto** [comment]
I have 2 différents indoors units : Split Carrier model 42QHG012D8S (x1) and Split Carrier model 42QHG009D8S (x2). Units outdoor are 38QHG009D8S (x2) and 38QHG012D8S.

Thank you :)

>

**Comment by hillaliy** [comment]
You can't use midea app and Homebridge at the same time. Try to use instead NetHome Plus app

**Comment by hillaliy** [comment]
> Thank you for your response. I don’t know that my models are U Midea. They are Carrier brand with Carrier Dongle (OSX103 model). They are contrôlable by Carrier and Midea app and account. I send you my account informations if you want. Good luck :)
> […](#)

Can you send me your account i'll make some tests

**Comment by mpetto** [comment]
Hello,
I have send to you my account access by mail.

for information, it is still impossible to change the state of the air conditioners, even when disconnected from the Midea application

Thank you :) 

Maxime P.

**Comment by addps-user** [comment]
Amazing plugin - thank you!

The dashboard of current settings is perfect and works in sync with settings made with the remote or NetHomePlus/Midea apps, but I have the same problem trying to control from Homebridge:

- [midea-air] Command was not accepted by device: xxxxxxxxxx (nnnnnnnnnnnnnn)


Using NetHomePlus instead of Midea app, or neither at the same time makes any difference, so it doesn't appear to be a login conflict.

My model is:

> BREEZELESS Series-/Indoor unit| MSFAAU. OSHRENS-ORDGGN BREEZELESS
> BREEZELESS Series-Outdoor unit MO301-094FNG-ORD6GIV/A) BREEZELESS

Given just how good everything else is, it feels (I'm hoping!) like it's a tiny tweak away.

Thanks in advance all!

**Comment by BorisMert** [comment]
Is it different with EU-SK103 ?  
Getting the same issue: [midea-air] Command was not accepted by device: 
with Midea Xtrem save 

Is this ac available in this version ? and with this dongle ?

**Comment by hillaliy** [comment]
If you get the message: command was not accepted......
this plugin don't support your AC.

**Comment by hillaliy** [comment]
Go to - Add Midea Mission II / U support
