### ISSUE TITLE
No water level for Midea Cube dehumidifier. 

### ISSUE THREAD

**Issue by magn2o** [hillaliy/homebridge-midea-air#27]
Make: Midea
Model: Cube (20 Pint)
Model #: MAD20S1QWT

Some functions seem to work. For example, I can toggle it on and off and it shows the humidity level. However, the water level always reports 0 and I cannot set the target humidity level. As shown below, it reports as 50% -- although I have it set to 30%.

> [11/8/2021, 1:02:29 PM] [midea-air] Updating accessory: Dehumidifier_5442 ([device id removed])
> [11/8/2021, 1:02:29 PM] [midea-air] [updateValues] Header + Command: 90,90,1,0,89,0,32,0,1,0,0,0,39,36,17,9,13,10,18,20,218,73,0,0,0,16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,170,32,161,0,0,0,0,0,3,3,65,33,0,255,3,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,11,36,164,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
> [11/8/2021, 1:02:29 PM] [midea-air] [MideaPlatform.ts] sendCommand (Intent: [updateValues] (fetch params?) attempt 1/2) success!
> [11/8/2021, 1:02:29 PM] [midea-air] [Dehumidifier] Current Humidity is 54
> [11/8/2021, 1:02:29 PM] [midea-air] [Dehumidifier] Target humidity is set to 50
> [11/8/2021, 1:02:29 PM] [midea-air] [Dehumidifier] Water level is at 0
> [11/8/2021, 1:02:29 PM] [midea-air] Power State is set to: true
> [11/8/2021, 1:02:29 PM] [midea-air] Operational Mode is set to: 0
> [11/8/2021, 1:02:29 PM] [midea-air] Fan Speed is set to: 80
> [11/8/2021, 1:02:29 PM] [midea-air] Swing Mode is set to: 2
> [11/8/2021, 1:02:29 PM] [midea-air] Eco Mode is set to: false
> [11/8/2021, 1:02:29 PM] [midea-air] Turbo Mode is set to: false
> [11/8/2021, 1:02:29 PM] [midea-air] Full data is [
>   '11001000', '1',        '1', '1010000',
>   '1111111',  '1111111',  '0', '110010',
>   '0',        '0',        '0', '0',
>   '0',        '0',        '0', '1100100',
>   '110110',   '1010010',  '0', '0',
>   '0',        '0',        '0', '1011',
>   '1101011',  '10001010', '0', '0',
>   '0',        '0',        '0', '0',
>   '0',        '0',        '0', '0',
>   '0',        '0',        '0', '0',
>   '0'
> ]
> [11/8/2021, 1:02:29 PM] [midea-air] [updateValues] Sent update command to: 161

**Comment by hillaliy** [comment]
I don't have Cube Dehumidifier to test it.

**Comment by ripperak** [comment]
I have similar problems with Midea MDDF-20DEN7 WiFi .On/Off and humidity level works.No mode choice available which makes dehumidifier to work in fan only mode.Water level shows 0 but i think this is due to model not having a choice other than full tank.
