### ISSUE TITLE
Comfee MDDF-20DEN7-WF

### ISSUE THREAD

**Issue by ansgarschulte** [hillaliy/homebridge-midea-air#29]
Hi,

i do net get any humidity data for my "Comfee MDDF-20DEN7-WF"

![image](https://user-images.githubusercontent.com/1299623/143237490-45714ddf-7270-4491-a2ec-450baf56f825.png)

Any Idea?
I use this plugin in iobroker via https://github.com/ioBroker/ioBroker.ham Plugin.
Thx

**Comment by hillaliy** [comment]
try to use this plugin on homebridge.

**Comment by ansgarschulte** [comment]
Ok. It is working homebridge! Great. 

I discovered that it is also somehow working in ham, but only gets updates after adapter restarts. 
But this should be a bug in ham. 

Thx

**Comment by Matzushub** [comment]
@ansgarschulte would you mind sharing your config here? I want to compare as I am using the same device as you.

**Comment by ansgarschulte** [comment]
@Matzushub 
here you are:
`{
    "interval": 30,
    "devices": [
        {
            "supportedSwingMode": "None",
            "fanOnlyMode": false,
            "OutdoorTemperature": false,
            "deviceId": "000000P0000000Q1237C9B4412360000"
        }
    ],
    "user": "abc@mail.com",
    "password": "password",
    "platform": "midea-air"
}`

**Comment by Matzushub** [comment]
@ansgarschulte thanks you. Looks very similar to mine. Your device is looks significantly different to what I get in the home app? I just get a 14digit number (no zeros). Did you somehow code your serial number into the device ID by adding zeros to the beginning and end?

**Comment by ansgarschulte** [comment]
@Matzushub I found it in the "NetHome Plus" App on the details page of the device. In the Sub Menü "..." and then in the "about" section: "Barcode Device"

**Comment by Matzushub** [comment]
@ansgarschulte thanks again. I was under the impression that w should take the serial number either out of apple's home app or from the Homebridge log.
@hillaliy could you confirm which way of retrieving the Device ID is correct? Does it make any noticeable difference which number we take?

**Comment by hillaliy** [comment]
In both ways it's OK.
I'm using the homebridge log.

**Comment by Draexl** [comment]
@ansgarschulte Hello, I have the same model. Can you also e.g. control the drying value? I can only turn the device on and off.

**Comment by ansgarschulte** [comment]
Hi
Only on off

**Comment by Draexl** [comment]
Too bad :-( you didn't find any other way to control this?
I use the ioBroker as the central unit.

**Comment by ansgarschulte** [comment]
I use also ioBroker. But it was good enough for now, for me

**Comment by hillaliy** [comment]
if someone will give me access to his dehumidifier I will try to fix it.

**Comment by hillaliy** [comment]
Fix on version 1.7.0

**Comment by Draexl** [comment]
Perfect thank you. What I also noticed when I make changes directly on the device, these changes are not transferred.

**Comment by Draexl** [comment]
Question: SerialID = DeviceID?

**Comment by hillaliy** [comment]
when you make changes on the device it take about 30 sec to update changes (next sync).
Serial ID = Serial ID
Device ID = Device ID
