### ISSUE TITLE
iOS 15 Doesn't Update Current Temperature in Real Time

### ISSUE THREAD

**Issue by jackklink** [hillaliy/homebridge-midea-air#31]
Just wondering if you have noticed that ever since iOS 15, current temperatures are not updated in HomeKit until someone has opened the Home app. In other words: If you have an automation setup that is triggered by a change in temperature, the automation does not trigger until the Home app has been opened and the AC "tile" has been viewed allowing the current temperature to update. 

Before iOS 15, current temperatures would update and trigger automations in real time without needing to open the Home app.

Any ideas for a workaround?

**Comment by hillaliy** [comment]
Hi, I'm on vacation. I'll check it out on weekend.

**Comment by jackklink** [comment]
@hillaliy Have you had a chance to play around with this? Am I crazy or is this an issue for everyone else too? Thanks

**Comment by hillaliy** [comment]
Not yet

**Comment by hillaliy** [comment]
No Solution yet

**Comment by thinkier** [comment]
I've observed this phenomenon and I got an off-the-shelf temperature probe to test it. I found a significant difference, it also doesn't seem to update all that regularly. I had it stuck at 0 degrees for a few hours last night for no apparent reason.

![image](https://user-images.githubusercontent.com/26728734/152633963-3885c91e-ec77-4767-ba01-b65572f46047.png)

I don't think there's an easy solution aside from directly interfacing another sensor under the hood as [Current Temperature is a required characteristic](https://developers.homebridge.io/#/service/Thermostat).

I'll update this thread and potentially create a PR when I figure out a workaround.

**Comment by hillaliy** [comment]
Hi, about the 0 degrees last night, there was a problem with Midea servers.
The sensor on the AC is not accurate.

**Comment by hillaliy** [comment]
Try latest version 1.4.4

**Comment by jackklink** [comment]
I think it has been fixed, but I am waiting for the temperatures to get warmer here in California to do a proper test.

I did one test with an automation and it appeared to work, but it can be finicky. I will keep an eye on it and update here. Thanks!

**Comment by hillaliy** [comment]
Good to hear
