### ISSUE TITLE
Senville US-OSK103

### ISSUE THREAD

**Issue by boboxx** [hillaliy/homebridge-midea-air#33]
I just installed a mini split system by Senville with the US-OSK103 USB module.  (FW 4.0.4) I have 3 heads connected to one condenser. I'm using HB 1.3.8 and plugin 1.4.0

I see this in the log and no error message:
[12/4/2021, 8:50:48 PM] [midea-air] Initializing midea-air platform...

But I don't get any new accessories showing up.

I think my config looks ok:
{
            "user": "senville@gmail.com",
            "password": "password",
            "interval": 30,
            "devices": [
                {
                    "deviceId": "P0000000Q130B23747BD04",
                    "supportedSwingMode": "Vertical",
                    "fanOnlyMode": true,
                    "OutdoorTemperature": true
                }
            ],
            "platform": "midea-air"
        }

**Comment by boboxx** [comment]
I got it working, I installed the Midea IOS app and redid my account in that application instead of the Senville Application. (It's the same app visually)

**Comment by hillaliy** [comment]
👍
