### ISSUE TITLE
Tile temperature value

### ISSUE THREAD

**Issue by boboxx** [hillaliy/homebridge-midea-air#36]
The circle value from the tile seems to be inaccurate and fixed as it never changes. I have a multi head unit (9k, 12k, 18k) on a single condenser (36k).

The tiles in HB and in IOS for the 9k and 12k are always at 27.5 and the 18k is always at 25.5

![Tiles](https://user-images.githubusercontent.com/15091037/145403067-88dc7952-80c4-4141-a485-89fdcd88d333.png)
![Tiles_setting](https://user-images.githubusercontent.com/15091037/145403069-b9fefbbe-e68b-4b7b-83ec-feef8430bf50.png)

**Comment by hillaliy** [comment]
What is the AC model?
This pluging design to control singles units.
I'll try to read about this model.

**Comment by hillaliy** [comment]
In the app you see 3 air conditioners?

**Comment by boboxx** [comment]
yes here is how it looks:
![IMG_0077](https://user-images.githubusercontent.com/15091037/145565332-63b37dc0-4ec4-4955-8eba-0744b31c73aa.PNG)

**Comment by hillaliy** [comment]
it supposed to work.
The circle value is the current temperature.
Try to disable the plugin then restart homebridge, then enable it and restart again. if it need try another restart to homebridge.
