### ISSUE TITLE
Command was not accepted by device:

### ISSUE THREAD

**Issue by onebluemandm** [hillaliy/homebridge-midea-air#37]
I get an error ~every 40 minutes:

"Command was not accepted by device:   <Device Name>    <Device ID>"

This is when idle, not trying to send any commands.

**Comment by hillaliy** [comment]
There is an interval that check the AC state.
Sometime Midea api don't respond, because of it you see the error message.
I can remove the message but not the interval.

**Comment by hillaliy** [comment]
fix with version 1.4.1

**Comment by onebluemandm** [comment]
Thank you, I appreciate the response.
