### ISSUE TITLE
Midea Prime MB-12N8D6-I Mission 2

### ISSUE THREAD

**Issue by steliosxilou** [hillaliy/homebridge-midea-air#39]
Hi there.

I can't turn on/off through home bridge my AC although i can see the temperature and that is running when i am turning it on from the remote control for some reason. 

Thank you and sorry for my english.

**Comment by hillaliy** [comment]
write brand and model

**Comment by hillaliy** [comment]
this plugin don't Support Mission II and U models

**Comment by steliosxilou** [comment]
Ok.

Thank you for your response.
