### ISSUE TITLE
Device id 

### ISSUE THREAD

**Issue by bibs0n** [hillaliy/homebridge-midea-air#4]
Hi, where can I obtain the device id?

**Comment by hillaliy** [comment]
Go to Homekit app. Enter the AC properties. It’s there.

**Comment by bibs0n** [comment]
This is the only info I can find within the home app 
![Uploading CD57E2A0-36F8-4FF7-8B84-836474C95795.jpeg…]()

**Comment by bibs0n** [comment]
![11DDFABD-38FA-409E-AF56-1ECFECD3EB59](https://user-images.githubusercontent.com/82181113/114135733-97755c00-9901-11eb-8284-2312be00fffd.jpeg)

**Comment by hillaliy** [comment]
Serial number = device id

**Comment by bibs0n** [comment]
Perfect I assumed this would be the case, after updating config file and opening home app, the air conditioning displays the correct temp and shows correct status, upon interacting with it it automatically returns not responding and says this way until I close home app and reopen it

**Comment by hillaliy** [comment]
The not responding issue is known. you don't need to close the Home app. just minimize the app and open again and it will fix.
I need to improve "updateValues".

**Comment by bibs0n** [comment]
Great thanks
