### ISSUE TITLE
Humidity set Level On App doesn’t match Homekit

### ISSUE THREAD

**Issue by K0pp3r** [hillaliy/homebridge-midea-air#40]
Per the plug-in, I was using Homekit and Nethome Plus. The current relative humidity matches, but the humidity set value doesn’t. The home app keeps reverting back to 30% regardless of what the app or physical device is set at. 

Also, can we add an option for “comfort setting” in Homekit?

**Comment by hillaliy** [comment]
Write your AC vendor and model.
about  "comfort setting" it don't support by HomeKit.

**Comment by K0pp3r** [comment]
Sorry about that. It is the Midea Smartdry Dehumidifier. Model #MAD50PS1WBL

**Comment by hillaliy** [comment]
Can you send me to my mail your user name and password to get feedback from dehumidifier?

**Comment by K0pp3r** [comment]
No I'm not giving you my username and password for my dehumidifier. Sorry.

**Comment by hillaliy** [comment]
OK thanks
