### ISSUE TITLE
Dehumidifier Per-Device Values

### ISSUE THREAD

**Issue by Matzushub** [hillaliy/homebridge-midea-air#41]
Hi there

First of all - a big thank you for this plugin.

I am trying this plugin out for my dehumidifier Comfee MDDF-20DEN7-WF by Midea.
I have set it up with login data and looked for the Serial Number of the humidifier in the home app. Afterwards I added this serial number in the config as Device ID.

This is the correct procedure?
```
 "user": "eMAIL",
            "password": "PWD",
            "interval": 30,
            "devices": [
                {
                    "deviceId": "318858375xxxxx",
                    "supportedSwingMode": "None",
                    "fanOnlyMode": false,
                    "OutdoorTemperature": false
                }
             ],
            "platform": "midea-air"
```

Device specific Values don't match. If I set the target humidity to 60% in the NetHome Plus App then this is also confirmed on the dehumidifier device display. But in the Home App it shows "Lowering to 50%".

Is this a known issue or did I do a mistake in the config?
Also Device Modes are not supported?

**Comment by hillaliy** [comment]
Hi! device mode is not supported.
about the target humidity I don't have Dehumidifier to test so I can't fix the problem.
If you want to send me your user and password i'll try to get feedback from your Dehumidifier.

**Comment by Matzushub** [comment]
@hillaliy  I can create a face account and share the email and pwd with you. How can I reach you in private?

**Comment by hillaliy** [comment]
We can use discord Yossi#1563

**Comment by Matzushub** [comment]
@hillaliy sent you friend request

**Comment by hillaliy** [comment]
The feedback from dehumidifier to Homebridge is OK.
HomeKit Relative Humidity work between 0%-100% (can't change it, Apple policy)
The value is like this:
35% = 0%
40% - 10%
45% = 20%
.
.
.
.
85% = 100%

**Comment by hillaliy** [comment]
https://github.com/hillaliy/homebridge-midea-air#dehumidifier-relative-humidity

**Comment by Matzushub** [comment]
@hillaliy 

Understood. Would it be possible to match the values like that? Through a lookup table in homebridge plugin?
Homebridge  :  HomeKit
35%  :  0%
35%  :  5%
35%  :  10%
35%  :  15%
35%  :  20%
35%  :  25%
35%  :  30%
35%  :  35%
40%  :  40%
45%  :  45%
50%  :  50%
55%  :  55%
60%  :  60%
65%  :  65%
70%  :  70%
75%  :  75%
80%  :  80%
85%  :  85%
85%  :  90%
85%  :  95%
85%  :  100%

This would push the mismatch of scales to the outer boarders of the scale which aren't used anyhow.

**Comment by hillaliy** [comment]
No Homekit value are 0-100 and the steps is 10

**Comment by Matzushub** [comment]
Dang. Is that limitation only for ACs and Dehumidifiers? For any other device HK allows any value between 0-100%, right?

Could this work?
Set Value in HomeKit -> homebridge sends this value to API

0% -> off
10% -> 35%
20% -> 35%
30% -> 35%
40% -> 40%
60% -> 60%
70% -> 70%
80% -> 80%
90% -> 85%
100% -> 85%

**Comment by hillaliy** [comment]
Need some motivation to sit on it.
