### ISSUE TITLE
OSK103 Mercury Air outdoor temperature not working 

### ISSUE THREAD

**Issue by stefan-MT** [hillaliy/homebridge-midea-air#43]
Everything works, except the outdoor temperature which doesn’t show up in homekit, outdoor temperature is set to true and can be seen on the NetHome plus app

**Comment by hillaliy** [comment]
Try to restart Homebridge

**Comment by stefan-MT** [comment]
It doesn't show up as a sensor or on the ac unit, AC unit only shows internal temp

**Comment by hillaliy** [comment]
It's supposed to show as external Accessory.
