### ISSUE TITLE
SK103 dongle

### ISSUE THREAD

**Issue by dhanzseros** [hillaliy/homebridge-midea-air#44]
Hey,

I tried to set up a Midea air conditioner to homebridge. It has SK103 wifi dongle with connected to the wireless network. The plugin found the ac, I can see the state, temp but I cannot turn on/off or set anything. It seems the command does not reach the ac. Should I buy another one type of dongle which is in the supported list? Thank you!

David

**Comment by hillaliy** [comment]
Hi there is OSK103 Mission II / U model that not fully supported by this plugin.
as you write it can see the state of the AC but not control it.
Check if this is your dongle model or write your AC model I'll check for you.
other model are supported.

**Comment by dhanzseros** [comment]
Hey there,

thanks for the superfast reply! :) The Midea device type is "msmabu-12hrdn8". Can I use it with another dongle which is compatible with Homebridge? Thanks for the reply!

Best,
David
