### ISSUE TITLE
Comfee Dehumidifier Turn off on target

### ISSUE THREAD

**Issue by b3z** [hillaliy/homebridge-midea-air#45]
It works quite well but...

Why does the dehumidifier not turn off when the target humidity is reached?

Also when setting the target humidity using the vertical slider in the home app it snapps back to the old setting?!

**Comment by hillaliy** [comment]
Does the dehumidifier turn off when you use the Midea app?

and for vertical slider look at readme.

**Comment by hillaliy** [comment]
This plugin don't suppose to turn off a device when it reached to target temperature / humidity
