### ISSUE TITLE
Brand New User, Onboarded through MLife App, Not a lot of logs

### ISSUE THREAD

**Issue by bwt615** [hillaliy/homebridge-midea-air#46]
Installed through homebridge UI. Get a:

[07/02/2022, 17:19:42] Loaded plugin: homebridge-midea-air@1.4.3
[07/02/2022, 17:19:42] Registering platform 'homebridge-midea-air.midea-air'

Then nothing. AC works fine through MLife app.

**Comment by hillaliy** [comment]
Turn on Homebridge Debug Mode from Homebridge settings and then capture more logs

**Comment by bwt615** [comment]
It's on debug mode - that's all I get

**Comment by hillaliy** [comment]
create account using Midea app

**Comment by bwt615** [comment]
That worked. Mlife app no.
