### ISSUE TITLE
Fahrenheit Temp at lowest is 63

### ISSUE THREAD

**Issue by bwt615** [hillaliy/homebridge-midea-air#48]
When in Midea app it is 62.

**Comment by hillaliy** [comment]
The Default unit is Celsius. The AC always expects a celsius temperature.
The Formula from Celsius to Fahrenheit is:
F = C * 1.8 + 32
In your example: 17C = 62.6F
HomeKit can't Show 62.6 so the number is round to the nearest integer 63.
Maybe Midea app round it down.
16C = 60.8F will round to 61
17C = 62.6F will round to 63
18C = 64.4F will round to 64
etc....

**Comment by bwt615** [comment]
The display on the unit rounds down too - might want to align for consistency. I get it, but people would notice :)


[https://i.imgur.com/zf87pbX.jpg]
Benjamin Wesley Thomas
m +1 (781) 864-3648 | f +1 (781) 787-2609
e ***@***.***<file:///private/var/mobile/Library/Mobile%20Documents/com~apple~CloudDocs/iOS%20Signatures/EmailSignature1.html#>
w www.benjaminwesleythomas.com<file:///private/var/mobile/Library/Mobile%20Documents/com~apple~CloudDocs/iOS%20Signatures/EmailSignature1.html#>
[https://i.imgur.com/LekBgmL.png]<https://twitter.com/benjaminwthomas> [https://i.imgur.com/lyRQWJR.png] <https://www.linkedin.com/in/benjaminwesleythomas/>


________________________________

**Comment by hillaliy** [comment]
try beta 1.4.4-beta.1

**Comment by hillaliy** [comment]
Fix with version 1.4.4
