### ISSUE TITLE
OSK102

### ISSUE THREAD

**Issue by dhanzseros** [hillaliy/homebridge-midea-air#49]
Hey,

I have changed the wifi dongle my SK103 to OSK102 but I have still the same thing. I can see all of the data of the air conditioner in Homebridge but I cannot control it. What do you think? Is there any solution to control it from Homebridge? I do not have any error in logs now. I disabled the plugin and re-enabled, after that disappear the login error logs.

Thanks!
David

**Comment by hillaliy** [comment]
Did you scan / add the new dongle to your account with midea app?

**Comment by dhanzseros** [comment]
Not the dongle, the air conditioner has been added to the account, the older one deleted and I have found the new ID in log and added to config. The homebridge log says Created air conditioner..etc. No error. I can control only from Official app.

**Comment by hillaliy** [comment]
That's interesting.
Maybe the models: Mission II / U / Blanc
Need deferent SetCommands.
