### ISSUE TITLE
Midea Account Authentication

### ISSUE THREAD

**Issue by jsholiday** [hillaliy/homebridge-midea-air#5]
Hello, 

I’m having trouble authenticating my Midea account. I’m able to communicate with this Midea unit through the Apple Home App upon 1st installation (on/off).

When I first restart homebridge I get an notification that my Midea account has been signed in at another location. This tells me that the credentials are correct and that the homebridge plugin is communicating with Midea’s servers. 

The unit turns on & off as I mentioned but eventually pulls a no response in the home app. The on/off still works even with the no response. 

Once I restart homebridge for the 2nd time to try to restart the plug-in to resolve the issue, I received a red wall of error messages in the homebridge log. 

[4/10/2021, 1:37:00 PM] [midea-air] [MideaPlatform.ts] sendCommand (Intent: [updateValues] (fetch params?) attempt 1/2) returned error The asyn reply does not exist 
[4/10/2021, 1:37:00 PM] [midea-air] [updateValues] Error sending the command: undefined. Trying to re-login before re-issuing command...
[4/10/2021, 1:37:00 PM] [midea-air] [updateValues] re-login attempt failed

**Comment by hillaliy** [comment]
This is known problem. I need to improve Send command and update state.
About Midea account, you can use only one connection so don't use midea app if you use homebridge plugin.

This plugin is still in development.

**Comment by jsholiday** [comment]
Hi @hillaliy, 

Thanks for the response & thanks for developing the plug-in. I've moved to a new place and was sad that I could no longer use my Google Nest thermostat. But hopeful now that I can bridge my mini split to HomeKit with this. 

Let me know if you need any help testing, etc.
