### ISSUE TITLE
Inventor

### ISSUE THREAD

**Issue by Devel1232** [hillaliy/homebridge-midea-air#50]
This Plugin support Midea providers dongle
my dongle is : EU-ODZ104 (INV)
but the message ai log is [midea-air] getUserList invalid response
i have to sign up an midea app  or the api does not working for me

**Comment by hillaliy** [comment]
Your dongle is Tuya EU-ODZ104.
Do you use Midea app or Tuya app?
This plugin don't support Tuya dongles.

**Comment by Devel1232** [comment]
this dongle is inventror and i use inventror app. i can login midea app with the same passwords but in midea app i cant add my device, help me if you can. if i buy another dongle like beko or midea ?
<img width="289" alt="Στιγμιότυπο 2022-02-10, 10 44 59" src="https://user-images.githubusercontent.com/99372383/153370426-3c46a39b-d0c9-4f3c-a808-c7b79f908a76.png"><img width="453" alt="Στιγμιότυπο 2022-02-10, 10 45 13" src="https://user-images.githubusercontent.com/99372383/153370493-45dae946-bcfa-440e-b193-130b44a81deb.png">

**Comment by hillaliy** [comment]
You need to login Midea app and add your AC.
