### ISSUE TITLE
Inventor de humidifier

### ISSUE THREAD

**Issue by Mitsosxat** [hillaliy/homebridge-midea-air#52]
Hello, I have an inventor dehumidifier and your plug in works like a charm. Is there any way to get a notification when it stops from fillin up with water? The machine stops and “p2” shows up, so it would be great to show on HomeKit whether pauses stops or else.

**Comment by Mitsosxat** [comment]
Also I just saw that I can only set to 30% in HomeKit. If I try another value it just goes back to 30%

**Comment by hillaliy** [comment]
I can't add notifications to HomeKit.
Does the plugin show you the water level correctly?
and about humidity level I need to check it. The problem that I don't have dehumidifier to test.

**Comment by Mitsosxat** [comment]
No it isn’t. It always shows 0% water level. Is there any setting I can config to make it into debug mode and send you the log?

**Comment by hillaliy** [comment]
the logs won't help.
I'll try to find a solution

**Comment by hillaliy** [comment]
try version 1.5.6
