### ISSUE TITLE
How to configure with MRCOOL?

### ISSUE THREAD

**Issue by friism** [hillaliy/homebridge-midea-air#55]
I'm trying to make this plugin work with 3rd gen DIY MRCOOL minisplit with the Alexa/Google-Home USB dongle installed. Initially set this up with the MRCOOL app which I assume won't work with this plugin since the plugin relies on communicating with the Midea cloud service. So I reset the USB controller dongle on the minisplit and tried registering the air handler with both the Midea and Nethome apps, but neither work even though I had the air handler in "AP" mode and connected to the air handlers wifi.

Is there some other trick or process to set up a MRCOOL air handler to be able to work with this plugin?

**Comment by hillaliy** [comment]
Hi sorry no. I you can't add your AC to Midea Cloud it won't work
