### ISSUE TITLE
Midea Air recognised but not sending commands

### ISSUE THREAD

**Issue by apfoto** [hillaliy/homebridge-midea-air#56]
Hi, 

I have a Midea split air conditioning unit (Model: MSEPBU-09HRFN8-QRD6GW). It's recognised by Apple home kit through homebridge and I can see the temperature, that it's on / off etc, but it can't send any commands. If I try to switch on/off or make changes through homekit it just doesn't respond at all. But if I make changes using the remote then I can see them in homekit. 

Any ideas highly appreciated! 

Thanks.

**Comment by hillaliy** [comment]
you probably have the U or Balnc Model
This plugin don't support that models
see https://github.com/hillaliy/homebridge-midea-air/issues/3
