### ISSUE TITLE
Frequent Error 

### ISSUE THREAD

**Issue by tjridge** [hillaliy/homebridge-midea-air#57]
Below is an error that shows up in the log once every 2 seconds: 
[MideaPlatform.ts] sendCommand (Intent: [updateValues] (fetch params?) attempt 1/2) returned error invalidSession, 3106

**Comment by hillaliy** [comment]
Maybe your using Midea Air App?

**Comment by hillaliy** [comment]
https://github.com/hillaliy/homebridge-midea-air#notes
