### ISSUE TITLE
Two Air Conditioners Units (Just One Works)

### ISSUE THREAD

**Issue by Raquiros** [hillaliy/homebridge-midea-air#58]
Both A/C Units shows in Homekit, the second one even pulls the outside temperature, however when I try to turn it on, it just attempts for about 10 seconds and then comes backs to off state (in Homekit, A/C doesn’t do anything.

First A/C Unit works flawlessly, if I swap the order the first one works ok…. Seems like the second one is always the problem…..

**Comment by hillaliy** [comment]
What's the models, and what App you'r using? if midea air https://github.com/hillaliy/homebridge-midea-air#notes

**Comment by surreyfull** [comment]
Hello 

I am having the same issue. Midea A/C unit. Shows up in HomeKit and confirms correct temperature. 
If I turn it on using Midea Air or NetHome Plus app then HomeKit will update to show it’s “Heating / cooling “ and correct temperature but I cannot control or turn on/off using HomeKit. It attempts for about 10 seconds and then goes back to off state in HomeKit while the unit does nothing. 

midea Air 
MA2-09NXD0-XI

"user": "email",
            "password": "password",
            "interval": 30,
            "devices": [
                {
                    "deviceId": "000000P0000000Q1F0C9D1C157330000",
                    "supportedSwingMode": "Both",
                    "temperatureSteps": 1,
                    "fanOnlyMode": false,
                    "OutdoorTemperature": false
                }
            ],
            "platform": "midea-air"

**Comment by hillaliy** [comment]
You have the following models: U / Blanc...
This plugin don't support them fully
https://github.com/hillaliy/homebridge-midea-air/issues/3

**Comment by surreyfull** [comment]
Thanks for responding. So I cannot use the plugin to control the unit?

**Comment by hillaliy** [comment]
not for now

**Comment by surreyfull** [comment]
ok thanks for your help. I have checked and its a Midea Blanc series with dongle OSK103
