### ISSUE TITLE
Showing FP in heating mode

### ISSUE THREAD

**Issue by snandor** [hillaliy/homebridge-midea-air#59]
Starting from plug-in version 1.4.6 , my device (type 172) cannot be set to heating. Instead of displaying the target heat temperature and heating, the device goes to FP mode. Heating is working fine in 1.4.4.

**Comment by hillaliy** [comment]
try 1.4.8

**Comment by snandor** [comment]
Heating mode is working fine again, thank you very much for the quick fix, appreciated!

**Comment by hillaliy** [comment]
👍
