### ISSUE TITLE
Not working on midea xtreme save

### ISSUE THREAD

**Issue by Shael08** [hillaliy/homebridge-midea-air#62]
Only the current room temperature reflected back to the home brdige.
 So i think there is some communication between the AC and the homebridge, but the AC is not recognizing any commands.

Model number: 
MG2X-12-SP Xtreme Save
MSAGBU-12HRFNX

**Comment by hillaliy** [comment]
Maybe it's one off these models
https://github.com/hillaliy/homebridge-midea-air/issues/3
