### ISSUE TITLE
Node 16.0 Recommendation

### ISSUE THREAD

**Issue by booruce** [hillaliy/homebridge-midea-air#63]
Hi,

Is it necessary to actually have Node 16.0 in order for this plugin to work properly? I run Homebridge on a Raspberry Pi which is still running Node 14.x by default. While it is possible to upgrade to Node 16 on a Pi it is not standard process and requires a lot of additional steps.

My question is does this Homebridge Plugin actually require Node 16 to run properly or is it just a standard warning message?

![image](https://user-images.githubusercontent.com/82563332/167075951-c8d60a79-55a0-41d1-896c-b21b9675afeb.png)

**Comment by hillaliy** [comment]
I also using Homebridge on Rpi (Docker installation latest version) works with node.js 16.15.0
You can update the plugin and stay with node.js 14.19.2
