### ISSUE TITLE
Support for Midea MG2X-12-SP

### ISSUE THREAD

**Issue by mikes7806** [hillaliy/homebridge-midea-air#64]
Hi, the device is showing up in HomeKit, but cannot be controlled at all.
Model: Midea MG2X-12-SP
User and pass set up in NetHome Plus app, and provided for config.
I cannot see any errors in Homebridge logs

**Comment by hillaliy** [comment]
This is one of the new models, and it not supported by this plugin.
If you wan't to see errors on logs you can enable debug mode on Homebridge.
You will see the error: SendCommand to: XXXXXXX (123456789) [sendUpdateToDevice] attempt 1/2 returned error: The asyn reply does not exist  (3176)

**Comment by mikes7806** [comment]
Yes, now I see :( Thanks anyway for the reply
