### ISSUE TITLE
Can Control Everything in HomeKit App, but Not Through Siri

### ISSUE THREAD

**Issue by peachiemoomoo** [hillaliy/homebridge-midea-air#65]
Hi, I have two (MAP14HS1TBL) Midea DUO Smart Inverter 14K BTU Portable Air Conditioners with Heat. I added them both through Homebridge and this plug-in, but when I try to control things through Siri, she says she either can't do that or can't find that item in my home. So far the things that I know don't work with Siri are changing temperature and fan speed. Is this a known issue, or is there anything I can do to fix this? I don't think this is a "U" or "Blanc" model?

**Comment by hillaliy** [comment]
It's an Apple bug. There is more bugs on HomeKit like Cameras.
Hope they will fix it on next version.

**Comment by peachiemoomoo** [comment]
Thank you so much for your quick response and this plug-in!
