### ISSUE TITLE
1.5 Broke B08886Q136

### ISSUE THREAD

**Issue by bwt615** [hillaliy/homebridge-midea-air#68]
It just disappeared from HomeKit. Can't re-add. No logs.

**Comment by hillaliy** [comment]
fix on 1.5.1

**Comment by bwt615** [comment]
Won't even load now:

[37m[01/06/2022, 16:37:01] [39m[33mThe plugin "homebridge-midea-air" requires Node.js version of >=16.0.0 which does not satisfy the current Node.js version of v14.17.4. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
