### ISSUE TITLE
Node JS error

### ISSUE THREAD

**Issue by bwt615** [hillaliy/homebridge-midea-air#69]
Won't even load now:

[37m[01/06/2022, 16:37:01] [39m[33mThe plugin "homebridge-midea-air" requires Node.js version of >=16.0.0 which does not satisfy the current Node.js version of v14.17.4. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m

@hillaliy 

__Originally posted by @bwt615 in https://github.com/hillaliy/homebridge-midea-air/issues/68#issuecomment-1144119368__

**Comment by hillaliy** [comment]
Upgrade your node

**Comment by hillaliy** [comment]
I'm using Homebridge on docker. Node.Js version 16.15.0 works perfect. Rpi 4
