### ISSUE TITLE
On/Off function not working

### ISSUE THREAD

**Issue by superdumnezeu** [hillaliy/homebridge-midea-air#71]
Hello, 

I managed to add my AC to the plugin, and the temperature is correctly detected. But for some reason the On/Off function does not work. Besides that, the state of the button in Homebridge does not change. 

Any ideas to fix this? 

![image](https://user-images.githubusercontent.com/45486773/171569969-67d965f0-d70b-4983-839a-dc74f7865ed6.png)

Thanks

**Comment by hillaliy** [comment]
Check if you AC is one off the Models: U, Blanc.....

**Comment by hillaliy** [comment]
There is an open issue for this.
Your AC isn't fully supposed by this plugin
