### ISSUE TITLE
Add Turbo Button functionality?

### ISSUE THREAD

**Issue by jackklink** [hillaliy/homebridge-midea-air#74]
My Pioneer (midea internals) Mini Split works great with this plugin, but would love the ability to trigger the TURBO button for the highest fan setting possible. It's even faster than the 75% (100%) fan speed that HomeKit is capable of controlling now. The TURBO button is separate in the NetHome app as well as on the remote.

**Comment by hillaliy** [comment]
HomeKit don't support Turbo mode.
To add this feature I need to add a Service, and make changes on Code.
I need time and motivation to do it.

**Comment by jackklink** [comment]
Haha I get it. Thanks for all you do with this plugin. Could be great to have the turbo mode just be 100% as an option instead of auto like it is now.

**Comment by hillaliy** [comment]
Turbo mode makes a conflict with Fahrenheit.
Don't have the time to seat on it
