### ISSUE TITLE
Midea XTreme Save Pro MGP2X12 status is shown but cannot be controlled

### ISSUE THREAD

**Issue by gklka** [hillaliy/homebridge-midea-air#75]
When I use NetHome Plus app and pair the AC with it, I am able to use your plugin in Homebridge. It displays my AC. It appears correctly in Home app and I can see the live status of it. But when I try to control the AC from the Home app, it just does nothing. At the next status update it bounces back to the previous value. Homebridge logs are also mute. Any clues? Is it a setup problem or is my AC not compatible?

**Comment by hillaliy** [comment]
Your AC is not fully compatible.
There is an open issue for it.

**Comment by gklka** [comment]
Which one? This? https://github.com/hillaliy/homebridge-midea-air/issues/3

**Comment by hillaliy** [comment]
yes
