### ISSUE TITLE
No sound when controlling the air conditioner

### ISSUE THREAD

**Issue by tomer2526** [hillaliy/homebridge-midea-air#77]
Hello,
I've been using this extension for a few months now and it works great!
The only problem I would like to solve is that there is no sound when turning on, off, changing temperature and any other action.
When you control the air conditioner through the NetHome Plus app there is a sound. 
I would love to know if this is solvable

**Comment by hillaliy** [comment]
Hi it's not a bug. It's on purpose.

**Comment by tomer2526** [comment]
Okay, is it possible to cancel it?

**Comment by tomer2526** [comment]
> Hi it's not a bug. It's on purpose.

Okay, is it possible to cancel it?

**Comment by hillaliy** [comment]
Some people like without sound and some with.
If I have time I'll add option to config.

**Comment by tomer2526** [comment]
Thank you very much for your time, I will wait patiently for the update

**Comment by hillaliy** [comment]
Hi
I add option on config to enable / disable the beep sound.
version 1.5.4
