### ISSUE TITLE
Doesn't respond with Node 16

### ISSUE THREAD

**Issue by bwt615** [hillaliy/homebridge-midea-air#78]
Since installing node 16 AC hasn't worked at all. No log errors.

**Comment by hillaliy** [comment]
Go to Homebridge settings and enable debug mode.
then send logs

**Comment by hillaliy** [comment]
There is No problem on this plugin.
Check your system again.

**Comment by bwt615** [comment]
Latest update fixed whatever my issue was.


________________________________
