### ISSUE TITLE
SK105 Dongle -  Midea AG2ECO

### ISSUE THREAD

**Issue by metaljay** [hillaliy/homebridge-midea-air#79]
Hi,

had [this](https://mideauk.co.uk/wp-content/uploads/2020/09/MIDEA_DATA_SHEETS_AGECO_WALL_MOUNTED_.pdf) fitted today, managed to get everything working via the 'Midea Air' app but when I use the same login via Homebridge nothing is detected - how do I find out the device ID or is this irrelevant? 

Homebridge just says:
`[midea-air] Initializing midea-air platform...`

**Comment by metaljay** [comment]
Edit: Solved! for anyone else that has this issue, you need to select the serial number as the device ID i.e. 'P0000000Q1D48457F9ZZZZ'

**Comment by metaljay** [comment]
So the device shows up under accessories but I can’t control it. I select it and can see options but nothing gets sent to the aircon unit

**Comment by hillaliy** [comment]
This plugin don't fully support OSK105

**Comment by metaljay** [comment]
Is there a view / plan to support this? Can I send any logs / dumps to assist?

**Comment by hillaliy** [comment]
Logs won't help.

**Comment by metaljay** [comment]
what is the recommended dongle to use? I recon I can buy another and get rid of this SK105

**Comment by hillaliy** [comment]
First check if your device can work with lower dongle.

**Comment by metaljay** [comment]
> First check if your device can work with lower dongle.
> I don't know if this dongle will work with my plugin.

Where in the world are you? I’ll buy you one to have a play around with as this could help lots of people. It’s just an ESPmodule so highly likely will work with the AC

**Comment by metaljay** [comment]
> I'll try to build one.

I’ve just donated £20, please buy one to save yourself time. Having read on telegram it appears the ESP can be switched out with units that support SK105 so we should be good!

**Comment by hillaliy** [comment]
Thanks.
I'll hope it will work.

**Comment by metaljay** [comment]
Did yours arrive?

**Comment by hillaliy** [comment]
I haven't ordered yet, I came back yesterday from vacation in Greece. Hope this helps clear my mind 😁

**Comment by metaljay** [comment]
> I haven't ordered yet, I came back yesterday from vacation in Greece. Hope this helps clear my mind 😁

All good, it was more if you manage to get your AC unit to work with that dongle then it can be an option to people who have incompatible units (as its relatively cheap compared to buying a SK102/3 dongle).

Mine should arrive in a few days from Ukraine to the UK, I've seen people have got it working with homeassistant so still hope out there for Homebridge :)

**Comment by metaljay** [comment]
Just to add, got my dongle and it works perfectly in my latest midea unit with ESP Home. Thought about doing a add on for that?

**Comment by hillaliy** [comment]
send me link to the project

**Comment by metaljay** [comment]
> send me link to the project

Hardware:
https://github.com/lizardsystems/midea-mini-dongle

config and firmware:
https://github.com/lizardsystems/midea-mini-dongle/blob/main/midea_ac.yaml

https://esphome.io/components/climate/index.html?highlight=climate

**Comment by metaljay** [comment]
did you ever buy the dongle I donated money for?

**Comment by hillaliy** [comment]
Yes, it's work only with lan.

**Comment by metaljay** [comment]
So, I’ve got my original SK105 dongle back in my AC, I’m running home assistant on docker with this: https://github.com/georgezhao2010/midea_ac_lan

I’ve also got it paired nicely in HomeKit so all works perfect. 

![144529A0-4D00-4F5D-9E07-3DE948D04363](https://user-images.githubusercontent.com/10380582/188285480-93570e1b-ba08-412f-be75-1c933249d356.png)
![Uploading 15660FAD-075D-4C1E-B136-BCAC920FF0BD.png…]()

**Comment by hillaliy** [comment]
I start a new plugin: https://github.com/hillaliy/homebridge-midea-lan
but my AC has OSK102 and I can't make tests for new devices.
Also I don't have enough time to continue with the new plugin.
