### ISSUE TITLE
Device becomes unresponsive and spams errors in the log

### ISSUE THREAD

**Issue by MikeytheSoulAce** [hillaliy/homebridge-midea-air#8]
After turning off the device, I get error spam in the log and the device doesn't turn on anymore. Here is the cascade of errors that occurs

`[5/11/2021, 8:24:41 PM] [midea-air] [updateValues] Error sending the command: undefined. Trying to re-login before re-issuing command...`
`[5/11/2021, 8:24:41 PM] [midea-air] [MideaPlatform.ts] sendCommand (Intent: [updateValues] (fetch params?) attempt 2/2) returned error invalidSession`
`[5/11/2021, 8:24:41 PM] [midea-air] [updateValues] sendCommand command still failed after retrying: undefined`
`[5/11/2021, 8:24:42 PM] [midea-air] [MideaPlatform.ts] sendCommand (Intent: [updateValues] (fetch params?) attempt 1/2) returned error invalidSession`
`[5/11/2021, 8:24:42 PM] [midea-air] [updateValues] Error sending the command: undefined. Trying to re-login before re-issuing command...`

**Comment by hillaliy** [comment]
Sometimes you'll see this message. This plugin is still in development.
