### ISSUE TITLE
Support voor Midea heatpump

### ISSUE THREAD

**Issue by PvdGulik** [hillaliy/homebridge-midea-air#81]
Hello,

is it possible to add support for midea heatpums like Midea M Thermal Arctic Series ATW Heat Pump
MHA-V16W/D2RN8-B, HB-A160/CGN8-B, HBT-A160/240CD30GN8-B

thanks,

**Comment by hillaliy** [comment]
I need the midea API for AirWaterHeater
and a device to connect to it.

**Comment by hillaliy** [comment]
Sorry can't add support for Midea heatpump
