### ISSUE TITLE
Fan mode is not available with type 172 device

### ISSUE THREAD

**Issue by snandor** [hillaliy/homebridge-midea-air#83]
Fan mode is not available with type 172 device, would it be possible to add? When set it to fan mode with ir remote, the plug-in shows “keep between xx-xx C” with auto mode.

Thank you in advance!

**Comment by hillaliy** [comment]
It's already exists. You can find it in plugin config

**Comment by snandor** [comment]
Of course the option is enabled in the plug-in config, but doesn’t appear in the function list. There are only auto, cool, heat and off options.
