### ISSUE TITLE
No outdoor temp sensor with type 172 device 

### ISSUE THREAD

**Issue by snandor** [hillaliy/homebridge-midea-air#84]
Would it be possible to add the outdoor temperature sensor for device type 172 please? It is available in the Nethome Plus app, but doesn’t appear in accessories even though it is enabled in plug-in config:
"OutdoorTemperature": true

Thank you in advance, great work anyways!

**Comment by hillaliy** [comment]
This function add separate service. Apple policy.

**Comment by snandor** [comment]
Unfortunately no separate devices are added, that is my problem here. 

Thanks!

**Comment by hillaliy** [comment]
Try to disable the plugin. Then restart Homebridge, enable it and restart again.
Other users reported that everything is OK. Also work perfectly on my device.

**Comment by snandor** [comment]
Unfortunately that did not help. Is there any way I can help to figure out why the outdoor temp and fan mode are missing? To get debug log from the plug-in maybe?

>

**Comment by hillaliy** [comment]
You can try to send logs, but as I told there is no problem with the plugin.
Works perfect at my AC and I checked with some more users.

**Comment by ngandhy** [comment]
@snandor - did you ever figure this out?
