### ISSUE TITLE
Fan mode is not available with type 172 device

### ISSUE THREAD

**Issue by snandor** [hillaliy/homebridge-midea-air#85]
Fan mode is not available with type 172 device, would it be possible to add for this device as well? When set it to fan mode with ir remote, the plug-in shows “keep between xx-xx C” with auto mode. Function is enabled in plug in config:
"fanOnlyMode": true

Plug-in only lists the below modes: auto, heat, cool, off. 

Thanks!

**Comment by hillaliy** [comment]
This function add separate service. Apple policy.

**Comment by snandor** [comment]
Unfortunately no separate devices are added, this is why opened the case :)

**Comment by hillaliy** [comment]
Try to disable the plugin. Then restart Homebridge, enable it and restart again.
Other users reported that everything is OK. Also work perfectly on my device.
