### ISSUE TITLE
Temperature Units Reverts to Celcius...

### ISSUE THREAD

**Issue by cbwilliamsnh** [hillaliy/homebridge-midea-air#86]
Any time I use HomeKit to change the attributes of the AC units, the temperature reading on the unit changes back to Celsius. I'm in the US and would like them to stay on Fahrenheit. 

I have three U-Shaped Smart Inverter Window Air Conditioners (two 12,000 BTU and one 8,000 BTU).

I'm a programmer so I'd be happy to help out if you can point me in the right direction.

Chuck

**Comment by hillaliy** [comment]
Hi any help will be helpful. If I know where is the problem I could fix it.
Midea change there protocol on the new models.
I'm using OSK102 and it's work perfect.

**Comment by cbwilliamsnh** [comment]
where do I find the API/Protocol documents?

**Comment by cbwilliamsnh** [comment]
And where you say "Home-Assistant" plugin, is that a Homebridge plugin or is that for their native iOS app?

**Comment by hillaliy** [comment]
https://github.com/nbogojevic/midea-beautiful-air

**Comment by hillaliy** [comment]
Do you have Discord?

**Comment by cbwilliamsnh** [comment]
DarkShadow6262#2357

**Comment by hillaliy** [comment]
Try version 1.6.1

**Comment by cbwilliamsnh** [comment]
Much better! Temperature units stay set to F when I do other commands. Only thing that I see still isn't working is the oscillate function.

**Comment by hillaliy** [comment]
will be fixed on next version.
I know whats the problem

**Comment by hillaliy** [comment]
try version 1.6.2

**Comment by cbwilliamsnh** [comment]
Works!!

Only thing that's left if being able to set/unset "Eco Mode"!

Chuck

**Comment by hillaliy** [comment]
Homekit don't support Eco / Turbo Mode
I don't plan to add outside accessories for this
