### ISSUE TITLE
Midea Xtreme Save control error

### ISSUE THREAD

**Issue by zds7htv** [hillaliy/homebridge-midea-air#87]
The feedback works fine, but you can't control it at all.  I set a state and nothing happens with the device.  After that, it returns to the state it was in in the homekit application.

**Comment by hillaliy** [comment]
Your device is not fully supported by this plugin.

**Comment by zds7htv** [comment]
Will I be able to control it somehow?

**Comment by hillaliy** [comment]
Hopefully

**Comment by zds7htv** [comment]
What does it take?

**Comment by hillaliy** [comment]
Time, motivation, Knowledge

**Comment by glampr** [comment]
Same things happens for Inventor AC, model NUVI - 09WF.
The plugin reads the state but cannot alter it (turn on/off).
How can we tell if it's supported or not? (besides the obvious that it's not working 😋)

**Comment by hillaliy** [comment]
Not fully supported

**Comment by hillaliy** [comment]
https://github.com/hillaliy/homebridge-midea-air/issues/3

**Comment by hillaliy** [comment]
There is an open issue to add support for that model.
So I'm closing this issue.
