### ISSUE TITLE
Temperature appears in Fahrenheit in home.app, but Celsius on HVAC

### ISSUE THREAD

**Issue by tehzimd** [hillaliy/homebridge-midea-air#9]
Hello there,

Running this plugin with homebridge 1.3.4 on an RPzero W, works very well from the user interface standpoint. Units displayed in home.app are in Fahrenheit, but the device readout displays units in Celsius. Not sure if there's a config somewhere that I'm missing or if this is a known issue.

HVAC unit is Midea U-shaped window unit. All other functions appear to be working as advertised. 

Any help would be appreciated!

**Comment by hillaliy** [comment]
It works fine for me.

**Comment by tehzimd** [comment]
Agree -- all functions work as advertised... but I'm wondering if there is a config to make the HVAC unit display temperature units in Fahrenheit.  Thoughts?

**Comment by hillaliy** [comment]
No the default is Celsius and you can’t change it to Fahrenheit.
At this point I’m not planning to add support for Fahrenheit
