### ISSUE TITLE
Plugin generated a warning from the characteristic

### ISSUE THREAD

**Issue by clipse2004** [hillaliy/homebridge-midea-air#91]
Hello, 
you since newest my log is spammed with the following message:

[homebridge-midea-air] This plugin generated a warning from the characteristic 'Target Humidifier-Dehumidifier State': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.

Can you help me? 

Thx

**Comment by pascals92** [comment]
same here... 
Docker Homebridge
Comfee Dehumidifier

This plugin generated a warning from the characteristic 'Target Humidifier-Dehumidifier State': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.

**Comment by hillaliy** [comment]
send full log

**Comment by hillaliy** [comment]
Did you try version 1.6.4?

**Comment by clipse2004** [comment]
Yep thx dude you fixed it ;)

**Comment by pascals92** [comment]
> Yep thx dude you fixed it ;)

confirmed, it works for me too

**Comment by hillaliy** [comment]
thanks for the update
