### ISSUE TITLE
Seeing error message...

### ISSUE THREAD

**Issue by cbwilliamsnh** [hillaliy/homebridge-midea-air#94]
```
[9/1/2022, 1:54:09 PM] [homebridge-midea-air] This plugin generated a warning from the characteristic 'Current Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
```

The error message was being repeated until I shutdown home bridge and restarted it. I tried restarting the Midea plugin child bridges via the UI but this did not resolve the issue.

**Comment by hillaliy** [comment]
What is your AC brand, model and dongle model?

**Comment by cbwilliamsnh** [comment]
one is: https://www.amazon.com/Midea-Inverter-Conditioner-Flexibility-Installation/dp/B08677DCKN/ref=sr_1_3?crid=21JXGO01C08N3&keywords=midea+u+shaped+window+air+conditioner&qid=1662057935&sprefix=midea%2Caps%2C177&sr=8-3

two are: https://www.amazon.com/Midea-Inverter-Conditioner-Flexibility-Installation/dp/B0867GMW9X/ref=sr_1_3?crid=21JXGO01C08N3&keywords=midea%2Bu%2Bshaped%2Bwindow%2Bair%2Bconditioner&qid=1662057935&sprefix=midea%2Caps%2C177&sr=8-3&th=1

Where do I find the logs?

**Comment by hillaliy** [comment]
Your models are not supported by this plugin

**Comment by hillaliy** [comment]
https://github.com/hillaliy/homebridge-midea-air/issues/3

**Comment by cbwilliamsnh** [comment]
Ok, but it's a year later and I'm able to use the plugin for the U AC units but it seems to get corrupted from time to time over long periods of use.

What do you propose as a solution? I can write code if you can point me to the proper API for my units and I can fork your repo and make the modifications that are needed for the AC units that I have.

**Comment by hillaliy** [comment]
I don't have a solution

**Comment by hillaliy** [comment]
Try version 1.6.7
Please confirm

**Comment by cbwilliamsnh** [comment]
Running it now! So far, no issues. Will let you know if it stops working.

**Comment by cbwilliamsnh** [comment]
Still has issues when running a long time. This morning I could only control the AC's via the Midea app, not via the Home app. I had to stop Homebridge and restart the homed daemon to get things back to operational.

**Comment by hillaliy** [comment]
Check your system.

**Comment by cbwilliamsnh** [comment]
ok, been up and running for 4 days with no issues! So you can now say the plugin supports the U AC's!!

**Comment by hillaliy** [comment]
Thanks for the reply

**Comment by cbwilliamsnh** [comment]
Where can I find the Midea API spec?

Thank you,
Chuck

--
