### ISSUE TITLE
Possible to disable eco mode?

### ISSUE THREAD

**Issue by kevincam** [hillaliy/homebridge-midea-air#97]
It looks like the eco mode flag isn't working or isn't being accepted, no matter what I try the AC returns eco mode = true when it turns on

**Comment by hillaliy** [comment]
Homekit don't support eco mode

**Comment by kevincam** [comment]
A toggle in HomeKit isn't needed, I just want to force it to turn off when a start command is sent

**Comment by hillaliy** [comment]
The default on this plugin is false.
