### ISSUE TITLE
LED keeps defaulting back on

### ISSUE THREAD

**Issue by bwt615** [hillaliy/homebridge-midea-air#98]
Never happens when using the app. LED setting keeps turning on. Can support for this be added in the app?

**Comment by hillaliy** [comment]
Yes it's can.
Need some time and motivation.

**Comment by bwt615** [comment]
Was this completed? Still happening every time :(

**Comment by hillaliy** [comment]
Did you give motivation?

**Comment by Stefan-83** [comment]
I would also be interested in a default setting for the LED (&beeping sound) to be switched off.
Use case is to be quiet for my little baby girl in the room :-)
